#! /bin/sh

ANT_HOME=/usr/pkg

if [ -f $HOME/.antrc ] ; then
  . $HOME/.antrc
fi

if [ "$ANT_HOME" = "" ] ; then
  # try to find ANT
  ANT_HOME=/usr/pkg
fi

if [ "$JAVA_HOME" != "" ] ; then
  if [ "$JAVACMD" = "" ] ; then
    JAVACMD=$JAVA_HOME/bin/java
  fi
else
  JAVA_HOME=/usr/pkg/java/sun-1.3.1
  if [ "$JAVACMD" = "" ] ; then
    JAVACMD=$JAVA_HOME/bin/java
  fi
fi

# add in the dependency .jar files
DIRLIBS="${ANT_HOME}/lib/java/ant/ant.jar ${ANT_HOME}/lib/java/ant/ant-nodeps.jar ${ANT_HOME}/lib/java/crimson.jar"
LOCALLIBS="/home/wistrand/knopflerfish.org/build/lib/xalan.jar"

for i in ${DIRLIBS} ${LOCALLIBS}
do
    # if the directory is empty, then it will return the input string
    # this is stupid, so case for it
    if [ "$i" != "${DIRLIBS}" ] ; then
        LOCALCLASSPATH=$LOCALCLASSPATH:"$i"
    fi
done

if [ "$CLASSPATH" != "" ] ; then
  LOCALCLASSPATH=$LOCALCLASSPATH:$CLASSPATH
fi

if [ "$JAVA_HOME" != "" ] ; then
  if test -f $JAVA_HOME/lib/tools.jar ; then
    LOCALCLASSPATH=$LOCALCLASSPATH:$JAVA_HOME/lib/tools.jar
  fi

  if test -f $JAVA_HOME/lib/classes.zip ; then
    LOCALCLASSPATH=$LOCALCLASSPATH:$JAVA_HOME/lib/classes.zip
  fi
else
  echo "Warning: JAVA_HOME environment variable is not set."
  echo "  If build fails because sun.* classes could not be found"
  echo "  you will need to set the JAVA_HOME environment variable"
  echo "  to the installation directory of java."
fi

# supply JIKESPATH to Ant as jikes.class.path
if [ "$JIKESPATH" != "" ] ; then
  if [ "$ANT_OPTS" != "" ] ; then
    ANT_OPTS="$ANT_OPTS -Djikes.class.path=$JIKESPATH"
  else
    ANT_OPTS=-Djikes.class.path=$JIKESPATH
  fi
fi

exec $JAVACMD -Xms64m -Xmx100m -classpath "$LOCALCLASSPATH" -Dant.home="${ANT_HOME}" $ANT_OPTS org.apache.tools.ant.Main "$@"
