#!/bin/sh

JAVA=java 					# the JRE to use
CLASSPATH_FLAG=-classpath			# the class path flag for the specific

# constants
KF_MAIN_CLASS=org.knopflerfish.framework.Main			   # path to main class
KF_CLASSPATH=framework.jar:$CLASSPATH				   # the class path to use 

# args always sent to the JRE
KF_JRE_ARGS="-Dorg.knopflerfish.framework.usingwrapperscript=true -Dorg.knopflerfish.framework.exitonshutdown=true -Dorg.osgi.supports.framework.extension=true -Dorg.osgi.supports.bootclasspath.extension=true"

EXIT_CODE_RESTART=200				

# Read all the args.
args_orig="" 		# all -xargs and -init args
args=""     		# like args excepts for -xargs and -init args
jre_args="" 		# arguments for the jre
fwdir=fwdir 		# default framework dir

# read the arguments
while [ -n "$1" ] 
do
  case "$1" in
      "-init"  ) args_orig=$args_orig" "$1;;
      "-xargs" ) shift; args_orig=$args_orig" -xargs "$1;;
#      "-D"* ) jre_args=$jre_args" "$1;;
      "--" ) shift; break;;
      * ) args=$args" "$1;;
  esac
  shift
done

# the rest is jre-specific args
while [ -n "$1" ]
do
  case "$1" in
      "-Dorg.osgi.framework.dir="* ) fwdir=`echo $1 | cut -c26-`;; # store fwdir.
  esac
  jre_args=$jre_args" "$1
  shift
done

# start kf
$JAVA $jre_args $KF_JRE_ARGS $CLASSPATH_FLAG $KF_CLASSPATH $KF_MAIN_CLASS $args $args_orig
retval=$?

#init-osgi-test-target.xargs
while [ "$retval" -eq $EXIT_CODE_RESTART ]
do
  # restart kf
  newclasspath=$KF_CLASSPATH:`cat $fwdir/classpath/system.classpath`
  $JAVA $jre_args $KF_JRE_ARGS $CLASSPATH_FLAG $newclasspath $KF_MAIN_CLASS $args 
  retval=$?
done

exit $retval
